# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-02-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430')),
                ('type', models.CharField(max_length=50, verbose_name='\u0422\u0438\u043f \u0441\u0430\u043c\u043e\u043b\u0435\u0442\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('airport_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0412\u044b\u043b\u0435\u0442\u0430')),
                ('start_time', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e \u0440\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u044e')),
                ('fact_time', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0444\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0435')),
                ('status', models.CharField(choices=[('\u0412\u044b\u043b\u0435\u0442\u0435\u043b', '\u0412\u044b\u043b\u0435\u0442\u0435\u043b'), ('\u041f\u0440\u0438\u0437\u0435\u043c\u043b\u0438\u043b\u0441\u044f', '\u041f\u0440\u0438\u0437\u0435\u043c\u043b\u0438\u043b\u0441\u044f'), ('\u0418\u0434\u0435\u0442 \u043f\u043e\u0441\u0430\u0434\u043a\u0430', '\u0418\u0434\u0435\u0442 \u043f\u043e\u0441\u0430\u0434\u043a\u0430'), ('\u0417\u0430\u0434\u0435\u0440\u0436\u043a\u0430', '\u0417\u0430\u0434\u0435\u0440\u0436\u043a\u0430')], max_length=300)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airplane')),
                ('city_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_end', to='flight.City', verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043f\u0440\u0438\u043b\u0435\u0442\u0430')),
                ('city_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_start', to='flight.City', verbose_name='\u0413\u043e\u0440\u043e\u0434 \u0432\u044b\u043b\u0435\u0442\u0430')),
            ],
        ),
    ]
